dist: xenial
language: ruby
rvm:
- 2.5.0
env:
- MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
- mkdir geckodriver
- tar -xvf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rails db:migrate --trace
- bundle exec rails db:test:prepare
- bundle exec rspec spec/
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: Tul13sxxx4pIC+K4kZQknqRqjONaLCkbrcDZEDDoTJGTgRAOv2hn9C3qlMxRqIpRMf2gmVgMxqWfLlITFhagffGbhQ0yAWeurYBeBr2YxKD6o7hdVFKrsygHT0nIS4yfaTH0sl2lh+yxfAplOEX1VizxMS9LhepBUh/juwFEV5H2rTJV2RnBxFqD7bbEeRugoIBIgiWs6TCnUQq1DuE1hNBJgFHf/mPBgDPWdU4BYpTqnA73VcE3OxFlpwvPD++bsEthqfQIpQ0M0kIKGq2vtJkm+QWiu45UpxOAKTsoh6IjtBKQI0HzSQLUkSIw4GUzuRWcEkRm4QgXf/kcXq63/Xl4FSNxl6AjOfOqxklA0pU3h5dUqe6D5xlO0QzUCuUkFjZf1MKtuBy4gvr0uEw7f2sa84dTHWyqFmkB4OAJuRfrtjlDH/JoXsKbxUOuXJWja4PjiCxuoowmLVNlvAbKIIniL+9mTAU1JwvWCV+5ebIGgZnQIzIg62r1vuH6dDLjeCgV58zg3Bz26ZYEfB4aIzB9v6hnP68m8BhYh5bqvhXDbTBP54eio9eEgQwlNz3RBJJJi3dB7ixrV7vaemlcZhASR1sGYZuTdtd3CMrEoxuTfK8i2YlwxrZpuCd8dBAakA8ssHVSzoUHCPy5UDmmCQ9Lj824XrfHDTW8B7sSr0U=
  run: rails db:migrate
  app: sme-organizer
  on:
    repo: mattwr18/sme-organizer
