dist: xenial
language: ruby
rvm:
- 2.5.0
env:
- MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
- mkdir geckodriver
- tar -xvf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rails db:migrate --trace
- bundle exec rails db:test:prepare
- bundle exec rspec spec/
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: CjdRh0sgcGj/u2HhOeX0KBrRkAq7f03Q5J3/ETZBu850GJzwh+K7Kkg4qEIgf287yGm50yy64uU/qnI1UBIJH0wTiLL/DUU0w7e0jLLoHwlgHDbkxpxDyavb2qXjmLycJsrcnnGiV3COIsOPq0YIUsQd51sAXVqheExZNk2s2LVsKzLURaKzx2+euWikZ3g4/kyShPqIl94akhOqdCtoSQsQDVEMUpx+KnawB+VMh9dDWPanYXYrsyGk5gVAEW1XVS24Yxh3Z6j16Vfg3otsDZ//qo/HxqmJpJmdK/GNHyV2fT9TxtlhrPJ9PChpdU09cShl1sW8JEURhexl9bmXf6Xe4249ZflrWq4WttwuoON5NfSIOZOCpHAufOwI+XocpJ8ejSkpn9bi+tlNrNrouJu4gl88xaOB8Sz5fDMUmDp+qFcKx8ywRFuzvP8SBVLJVsQ+0eVq1dm7EpMe8UkeQvu0G9aWq+AXbUU70czZuup/B/iEhbAejIf8/8xAeD8DxwBraUpBcVslfMeM2du8LBjKMZOJVfSAi4NdtdcgwcC3yoCodzDzH4FHSQun6zabB7H0U1k8e1zeZx5NnXtk+AffW6RFqoJjsw1sm2+HuNS0rz+eUfpZDHMHpa2Bxj6iipFlFda/BgWnzVueCoYecuuqjo+tVR2yM2cjrO62BWw=
  run: rails db:migrate
  app: sme-organizer
  on:
    repo: mattwr18/sme-organizer
