dist: xenial
language: ruby
rvm:
- 2.5.0
env:
- MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
- mkdir geckodriver
- tar -xvf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rails db:migrate --trace
- bundle exec rails db:test:prepare
- bundle exec rspec spec/
deploy:
  provider: heroku
  api_key:
    secure: vqQQ3BmSl5v872HM4ujKq9jV5Y/Q4WvDWYFqEacC4GKmq7FSjmpVM/Ccox6lrkPLRAIMCdo1w86PjIIF1nnWAa356z8Uh0a5O8o5zH3jfgR+aJNC3CX8MoYSzWl5QkoDnffbARHXfAgKIoxKu+Pt7K158dO80YzTVbrmR/hVE+531nWrZXecMue15aBDY5mOP1xvgPECUsMd4wArT7bDBobQdSnm2Up7D/OHoQCgGoT6E/hhuRDAUrIfh6c/embaf7uHCiiNsTxNYjhxMiqtXKojTu9DRBe8CiQsncs5hGV5ITLK1AWD7UsQbJApL7pDt1JNIR1OSwRc1S7Y3G1zNf4KVF/0eiqNqnZp/tsUT3ZWgF6AO2LJX7IyAMhIdfv6eo+Ikul6wIQC/ujRq1NQUPncvTFRyZhrxA21l8or+b5STw5GVOAjaKXi59ndNMKosaZHWVuoMnw7Qk40UKbkgQjWoXSuY9bK4VtYSwBbGlpS7f5oOvdnxxFkGmlljPJNkjbeiJPMdLoGtWTkcQEVDwd+AxIgX77T6ScowcZ/A88Yoc5sV280K70+yzOC+XWUUmfI9zv+hzmq6tFuczszF9q8XRJFsJh+Gvrki3uocgtbMtHoyNhwuAzso03qJHKV6l8jFL4QDx5SYmGwDEkf+eRpGC1hCa/B+Nmw2c3UqNI=
  run: rails db:migrate
  app: sme-organizer
  on:
    repo: mattwr18/sme-organizer
