dist: xenial
language: ruby
rvm:
- 2.5.0
env:
- MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
- mkdir geckodriver
- tar -xvf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rails db:migrate --trace
- bundle exec rails db:test:prepare
- bundle exec rspec spec/
deploy:
  provider: heroku
  api_key:
    secure: oCSqIprut75TBWjheZYNYDfWAT6OddbqPEImOvU2te9+q6ZAtsEytx+MJKm8y7ILbEy8eNq75h/pWjugJ/9VDGEM7Ikw8CjFWZl7I565M0ojBPt5MGUlCvSa/kk0ulVn+hW9vhC1v6FACqIy6MgZaQzXN8EWJxAs+NYE9E7iN5dcxqpi7MrmoKSMLGm6U1Ns+JIWSnT4X6927i1QYRZ67EuyUfEWuZ7eE6XUeRH8yu1DK2p+FnAePcnoXWR89cxHrd5Wi2f5K7SegtnfsoSPASJVNx23B1rFC0K3bOQAjKVk9wqyujhaBH87wIkmLJjR6rTrojMkqUez48ekD64FVIe+tFgST2hOsfp5Ky6C2EpGqS2PBekeYoVNsDFhlyRyHVK8uMMCNoZD8FJYwGC3WZrTEqTiyaug9VBKDZ+DdfpPLUZ/IvI8Agsn7zsR0PrWJQGiIz2jdDl5bcCZMAOPS08Rs/Pdf1085I0jpF9ZT8TcG2LLyuv4Ie3KSd87Y98/w1TJNptgWShHcQuHjCmfrkMQ5okReZmh4soC7rDhQPojd9uBrV7sECKyMkMVUf65JgoKMAbu1RGV6L79uQkucI783lCISo3X0+p/USy6e9p8+Ef5HKo7LSYNcE6xLmpTmF5ppipe5w5rvZXENsNHeGwI9BRsk/acLmbikEQuk3I=
  app: sme-organizer
  on:
    repo: mattwr18/sme-organizer
