language: ruby
rvm:
- 2.5.0
services:
  - postresql
script:
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rails db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
deploy:
  api_key:
    secure: j3gvrX/faGfDWFzzE2OArRx1LzkogLVSYlxzbgDsgT1S7M1FAozQJlZ9cvvn0KY3PMGHtKO3+tz9+S0TWJqwWE1KdMNYJgdaj+jz3H05pneI+mXFIle5DIWpTamJPKjwVlAJSXgErBknkkw9fdQRwDyyel7ph/aQcYFUxvrpQrcc41ddfDQyuTitPEmqqI/9KoEulY4Pvkz3w10YUJxS+vN3pM1wAlG9aIMWLRJWYAkPv00IyS1R4WgYMSPNN5mjRLl0wpnunSaamXOAfPE5pUoX8pYk++JjSo0XS7KQhqkcAodz/h3RDRpZn2UaVAUcaQbGoZfjm8i9nuYYlQDmvJrp8UyKA7PmU6xHi0VDe/+LiU4OBSTiS3TT3itSkbAFRh3GSGBDG89ZFeNY6gsuxwqxrHQj8dmhLqnSWBHNwLx6h6xLfVDk2akNKOI/DRNcH/cFPkevHCrdz2ICKxvhWLDyJF6hZabnAJeSDwvNPfcuUAEJk4PXArSg/ldeWzw3OeyDjG4k7DFN3aANAYASB8hgFQA0Eo6Hgs0HHZIzpeh8cm8ZTQl5TaF73sQsNj04qBN+ZsVLsIcnW/03pAXVTUoccn2ZFvtaiUyLJyzdjDiT4AeavOebFt2d9P/mDur1WRI7ywDsuBugGcIbPjB9EauehAN0jwW9xhkPBOkP2ME=
